# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

variables:
  buildConfiguration: 'Release'
  webDriverVersion: '75.0.3770.140'
  isRemote: true

trigger:
- master

pool:
  vmImage: 'windows-latest'

steps:

- task: SonarCloudPrepare@1
  displayName: 'Prepare SonarCloud analysis'
  inputs:
    SonarCloud: 'SonarCloud'
    organization: 'aqualityautomation'
    projectKey: 'aquality-automation_aquality-selenium-core-dotnet'
    projectName: 'aquality-selenium-core-dotnet'
    projectVersion: '$(Build.BuildNumber)'

- script: dotnet build Aquality.Selenium.Core/Aquality.Selenium.Core.sln -c $(buildConfiguration)
  displayName: 'Build solution - $(buildConfiguration)'

- task: Windows Application Driver@0
  displayName: 'Start WinAppDriver'
  inputs:
    OperationType: 'Start'
- task: DotNetCoreCLI@2
  displayName: 'Run tests'
  inputs:
    command: 'test'
    projects: '**/*Tests*/*.csproj'
    arguments: -c $(buildConfiguration) --no-build
    publishTestResults: true
- task: Windows Application Driver@0
  displayName: stop WinAppDriver
  inputs:
    OperationType: 'Stop'
  
- task: SonarCloudAnalyze@1
  displayName: 'Run SonarCloud code analysis'
  continueOnError: true

- task: SonarCloudPublish@1
  displayName: 'Publish SonarCloud quality gate results'
  continueOnError: true